// src/app/index.tsx
import * as React from "react"
import * as ReactDOM from "react-dom"
import styled from "../styled"
import { ThemeProvider, createGlobalStyle } from "../styled"
import * as Toolbar from "../tools/toolbar"
import * as Layers from "../layers/view"
import * as Input from "../input"
import * as Canvas from "../canvas"
import * as Setup from "./setup"
import { SetOnce, FrameStream, CancelFrameStream, Lazy, Store } from "../util"
import * as Buttons from "../views/buttons"
import * as Debugging from "../debugging"

// HMR hooks
declare global {
    interface NodeModule {
        readonly hot?: {
            accept(): void
        }
    }
}

const Wrapper = styled.div`
    display: flex;
    flex-direction: row;
    justify-content: space-between;
    width: 100%;
    box-sizing: border-box !important;

    ** {
        margin: 0;
        padding: 0;
        border: 0;
        outline: none;
        box-sizing: inherit;
    }
`

const BottomLeft = styled.div`
    position: absolute;
    left: 0.5rem;
    bottom: 0.5rem;
`

const BottomRight = styled.div`
    position: absolute;
    right: 0.5rem;
    bottom: 0.5rem;
`

const AppContainer = styled.div`
    font-family: ${p => p.theme.fonts.normal};
`

const GlobalStyle = createGlobalStyle`
    body {
        background-color: ${p => p.theme.color.background.toStyle()};
    }
`

class Painter extends React.Component<{}, Canvas.State> {
    private readonly removeInputListeners: SetOnce<Input.RemoveListeners>
    private readonly cancelFrameStream: SetOnce<CancelFrameStream>
    private readonly canvas: SetOnce<Canvas.Canvas>
    private readonly store: Store<Canvas.State, Canvas.EphemeralState, Canvas.CanvasMsg>
    private readonly sender: Canvas.MsgSender
    private htmlCanvas: HTMLCanvasElement | null

    constructor(props: {}) {
        super(props)
        this.state = Canvas.initState()
        this.removeInputListeners = new SetOnce()
        this.cancelFrameStream = new SetOnce()
        this.canvas = new SetOnce()
        this.store = Store.create<
            Canvas.State,
            Canvas.EphemeralState,
            Canvas.CanvasMsg,
            Canvas.Effect
        >({
            initialState: this.state,
            initialEphemeral: Canvas.initEphemeral(),
            effectsHandler: new Lazy(() => (ef: Canvas.Effect) => this.canvas.value.handle(ef)),
            forceRender: () => this.forceUpdate(),
            update: Canvas.update,
        })
        this.sender = Canvas.createSender(this.store.send)
        this.htmlCanvas = null
    }

    render() {
        const state = this.store.getState()
        const sender = this.sender

        return (
            <React.StrictMode>
                <ThemeProvider theme={state.theme}>
                    <AppContainer>
                        <GlobalStyle />
                        <Wrapper>
                            <Toolbar.View
                                tool={state.tool}
                                transientState={{ isDetailsExpanded: true }}
                                msgSender={sender.tool}
                            />
                            <canvas
                                width="800"
                                height="800"
                                key="muh-canvas"
                                ref={x => (this.htmlCanvas = x)}
                                style={{ cursor: "crosshair" }}
                            />
                            <div style={{ width: "14rem" }}>
                                <Layers.LayersView layers={state.layers} sender={sender.layer} />
                            </div>
                        </Wrapper>
                        <BottomLeft>
                            <Buttons.PrimaryButton onClick={sender.randomizeTheme}>
                                Next theme
                            </Buttons.PrimaryButton>
                        </BottomLeft>
                        {process.env.NODE_ENV === "development" && (
                            <BottomRight>
                                <Debugging.DebugWindow state={state} />
                            </BottomRight>
                        )}
                    </AppContainer>
                </ThemeProvider>
            </React.StrictMode>
        )
    }

    componentDidMount() {
        console.log("Painter mounted")
        const htmlCanvas = this.htmlCanvas
        if (htmlCanvas == null) throw "Canvas not found"

        {
            const canvas = Canvas.Canvas.create(htmlCanvas, this.state, {
                onStats: stats => {
                    console.log(stats)
                },
            })
            if (canvas === null) throw "Failed to initialize Canvas"

            this.canvas.set(canvas)
        }

        this.removeInputListeners.set(
            Input.listen(htmlCanvas, {
                click: this.sender.onClick,
                release: this.sender.onRelease,
                move: x => {
                    /**/
                },
                drag: this.sender.onDrag,
            })
        )
        this.cancelFrameStream.set(FrameStream.make(this.sender.onFrame))

        if (process.env.NODE_ENV !== "production") {
            Setup.setup(() => this.state, this.sender)
        }
    }

    componentWillUnmount() {
        this.removeInputListeners.value()
        this.cancelFrameStream.value()
        this.canvas.value.dispose()
        console.log("Painter unmounted")
    }

    componentDidUpdate() {
        this.canvas.value.update(this.state)
    }
}

{
    const rootElement = document.getElementById("canvas-root")

    if (rootElement === null) {
        throw "canvas-root not found"
    }

    ReactDOM.render(<Painter />, rootElement)

    if (typeof module.hot === "object") {
        module.hot.accept()
    }
}

// src/lib/App.svelte
<script lang="ts">
    import * as Toolbar from "./ui/toolbar/index.js";
    import { Layers } from "./ui/layers/index.js";
    import { Surface } from "./ui/components/surface/index.js";
    import { MiniMap } from "./ui/mini-map/index.js";
    import { Debugging } from "./ui/debugging/index.js";
    import PrimaryButton from "./ui/components/buttons/primary-button.svelte";
    import { onBeforeUnload, getCameraTransform } from "./AppUtil.js";
    import { onPageMount, canvasState, canvasInfo, canvasSender } from "$lib/ui/state.js";

    let canvasRef: HTMLCanvasElement | undefined;
    $: state = $canvasState;
    $: sender = $canvasSender;

    onPageMount(() => canvasRef);

    if (!import.meta.env.DEV) {
        onBeforeUnload();
    }
</script>

<div class="appContainer">
    <div class="wrapper">
        {#if sender && state}
            <Toolbar.Toolbar
                sender={sender.tool}
                tool={state.tool}
                transientState={{ isDetailsExpanded: true }}
            />
        {/if}
        <canvas
            class="canvas"
            bind:this={canvasRef}
            width={$canvasInfo.resolution.x ?? 800}
            height={$canvasInfo.resolution.y ?? 800}
            style={!state ? undefined : `transform: ${getCameraTransform(state.tool.camera)}`}
        />
        {#if sender && state}
            <div class="layersViewContainer">
                <Surface>
                    <MiniMap camera={state.tool.camera} sender={sender.tool.camera} />
                </Surface>
                <Layers layers={state.layers} sender={sender.layer} />
            </div>
        {/if}
    </div>
    {#if sender && state}
        <div class="bottomLeft">
            <PrimaryButton on:click={sender.randomizeTheme}>Next theme</PrimaryButton>
        </div>
    {/if}
    {#if import.meta.env.DEV}
        <div class="bottomRight">
            <Debugging />
        </div>
    {/if}
</div>

<style lang="scss">
    @import "../lib/ui/theme.scss";

    .wrapper {
        display: flex;
        flex-direction: row;
        justify-content: space-between;
        width: 100%;
        box-sizing: border-box !important;

        ** {
            margin: 0;
            padding: 0;
            border: 0;
            outline: none;
            box-sizing: inherit;
        }
    }

    .bottomLeft {
        position: absolute;
        left: 0.5rem;
        bottom: 0.5rem;
    }

    .bottomRight {
        position: absolute;
        right: 0.5rem;
        bottom: 0.5rem;
    }

    .appContainer {
        width: 100vw;
        height: 100vh;
        overflow: hidden;
        font-family: $fonts-normal;
    }

    .layersViewContainer {
        display: flex;
        flex-direction: column;
        gap: 1rem;
        width: 14rem;
        z-index: 1;
    }

    .canvas {
        cursor: crosshair;
        z-index: 0;
    }
</style>
