// package/ui/debugging/scripting.svelte
<script>import { onMount } from "svelte";
import { debuggingGl } from "../state";
let code = "";
const onKeyboard = (ev) => {
    if (ev.key === "Enter" && !ev.shiftKey && !ev.altKey) {
        ev.preventDefault();
        try {
            /* eslint-disable-next-line no-eval */
            console.debug(`Evaluating {| ${code} |}`);
            const gl = $debuggingGl;
            console.debug(eval(code));
        }
        catch (err) {
            console.error("Error: ", err);
        }
        code = "";
    }
};
onMount(() => {
    window.addEventListener("keydown", onKeyboard);
    return () => {
        window.removeEventListener("keydown", onKeyboard);
    };
});
</script>

<div>
    <div>
        Variables
        <ul>
            <li>
                <span class="monospaced">gl</span>: WebGLRenderingContext
            </li>
        </ul>
    </div>
    <textarea class="codeInput" bind:value={code} />
</div>

<style>/*
 * css variables don't get typechecked, and it's very hard to refactor them, so we prefer
 * to use these scss variables that refer to the css variables, since the scss has to be compiled,
 * and the compilation will fail when scss-variables are undefined.
 */
.monospaced {
  font-family: var(--fonts-monospace);
}

.codeInput {
  font-family: "Courier New", Courier, monospace;
  background-color: var(--color-primary);
  color: var(--color-onPrimary);
  border-radius: 0.25rem;
  padding: 0.25rem;
}</style>

// src/debugging/scripting.tsx
import * as React from "react"
import styled from "../styled"
import { SetOnce } from "../util"

const Monospaced = styled.span`
    font-family: "Courier New", Courier, monospace;
`

const CodeInput = styled.textarea`
    font-family: "Courier New", Courier, monospace;
    background-color: ${p => p.theme.color.primary.toStyle()};
    color: ${p => p.theme.color.onPrimary.toStyle()};
    border-radius: 0.25rem;
    padding: 0.25rem;
`

export interface ScriptingProps {
    readonly gl: SetOnce<WebGLRenderingContext>
}

export function Scripting(props: ScriptingProps) {
    const [code, setCode] = React.useState("")

    function onKeyboard(ev: React.KeyboardEvent<HTMLTextAreaElement>) {
        if (ev.key === "Enter" && !ev.shiftKey && !ev.altKey) {
            ev.preventDefault()
            try {
                /* eslint-disable-next-line no-eval */
                console.log(eval("var gl = props.gl.value;\n" + code))
            } catch {}
            setCode("")
        }
    }

    return (
        <div>
            <div>
                Variables
                <ul>
                    <li>
                        <Monospaced>gl</Monospaced>: WebGLRenderingContext
                    </li>
                </ul>
            </div>
            <CodeInput
                value={code}
                onChange={ev => setCode(ev.target.value)}
                onKeyDown={onKeyboard}
            />
        </div>
    )
}
