// src/views/surface.tsx
import * as React from "react"
import styled from "../styled"

export const SurfaceLook = styled.div`
    background-color: ${p => p.theme.color.surface.toStyle()};
    color: ${p => p.theme.color.onSurface.toStyle()};
    box-shadow: ${p => p.theme.shadows.surface};
`

export const Surface = styled(SurfaceLook)`
    display: flex;
    align-items: center;
    width: 100%;
    overflow: hidden;
    white-space: nowrap;
    user-select: none;
`

// src/lib/ui/components/surface/surface.svelte
<div class="surface">
  <slot />
</div>

<style lang="scss">
  @import "../../theme.scss";

  .surface {
    background-color: $color-surface;
    color: $color-onSurface;
    box-shadow: $shadows-surface;
    pointer-events: all;
    display: flex;
    align-items: center;
    width: 100%;
    overflow: hidden;
    white-space: nowrap;
    user-select: none;
  }
</style>
