// src/components/menu.tsx
import * as React from "react"
import styled, { Rem } from "../styled"
import { ZipperList } from "../zipperList"

export interface Props<a> {
    readonly choices: ZipperList<a>
    readonly show: (val: a) => string
    readonly onSelect: (val: a) => void
}

const Container = styled.div`
    background-color: ${p => p.theme.color.surface.toStyle()};
    color: ${p => p.theme.color.onSurface.toStyle()};
    min-width: 6rem;
`

const SelectedDisplayCommon = styled.div`
    cursor: pointer;
    text-align: center;
    min-width: 100%;
    padding: 0.25rem 0.5rem;
    border-radius: 0.25rem;
`

const SelectedDisplay = styled(SelectedDisplayCommon)`
    &:hover {
        background-color: ${p => p.theme.color.secondary.toStyle()};
        color: ${p => p.theme.color.onSecondary.toStyle()};
    }
`

const SelectedDisplayExpanded = styled(SelectedDisplayCommon)`
    background-color: ${p => p.theme.color.secondary.toStyle()};
    color: ${p => p.theme.color.onSecondary.toStyle()};
`

const SelectableOptions = styled.div`
    position: absolute;
    flex-direction: column;
    min-width: 6rem;
    margin-top: 1px;
    background-color: ${p => p.theme.color.surface.toStyle()};
    color: ${p => p.theme.color.onSurface.toStyle()};
    box-shadow: ${p => p.theme.shadows.menu};

    > :first-child {
        border-top-left-radius: 0.25rem;
        border-top-right-radius: 0.25rem;
    }
    > :last-child {
        border-bottom-left-radius: 0.25rem;
        border-bottom-right-radius: 0.25rem;
    }
`

const OptionCommon = styled.div`
    cursor: pointer;
    padding: 0.25rem 0.5rem;
`

const OptionDefault = styled(OptionCommon)`
    &:hover {
        background-color: ${p => p.theme.color.secondaryLight.toStyle()};
    }
`

const OptionSelected = styled(OptionCommon)`
    background-color: ${p => p.theme.color.secondary.toStyle()};
    color: ${p => p.theme.color.onSecondary.toStyle()};
`

interface State {
    readonly isExpanded: boolean
}

export class Menu<a> extends React.Component<Props<a>, State> {
    state = { isExpanded: false }
    container: HTMLDivElement | null = null
    listeningToGlobalClick: boolean = false

    render(): JSX.Element {
        const { choices, show } = this.props

        return (
            <Container onBlur={this.closeMenu}>
                <div ref={x => (this.container = x)}>
                    {this.state.isExpanded ? (
                        <>
                            <SelectedDisplayExpanded onMouseDown={this.closeMenu}>
                                {show(choices.focus)}
                            </SelectedDisplayExpanded>
                            <SelectableOptions
                                style={{
                                    marginTop:
                                        "calc(-0.5rem - " +
                                        this.container!.getBoundingClientRect().height +
                                        "px)",
                                }}
                            >
                                {choices.getLeft().map(value => (
                                    <OptionDefault
                                        key={show(value)}
                                        onClick={() => this.closeAndCallback(value)}
                                    >
                                        {show(value)}
                                    </OptionDefault>
                                ))}
                                <OptionSelected key={show(choices.focus)} onClick={this.closeMenu}>
                                    {show(choices.focus)}
                                </OptionSelected>
                                {choices.getRight().map(value => (
                                    <OptionDefault
                                        key={show(value)}
                                        onClick={() => this.closeAndCallback(value)}
                                    >
                                        {show(value)}
                                    </OptionDefault>
                                ))}
                            </SelectableOptions>
                        </>
                    ) : (
                        <SelectedDisplay onMouseDown={this.openMenu}>
                            {show(choices.focus)}
                        </SelectedDisplay>
                    )}
                </div>
            </Container>
        )
    }

    componentDidUpdate() {
        if (this.state.isExpanded) {
            if (!this.listeningToGlobalClick) {
                document.body.addEventListener("mousedown", this.onGlobalClick, {
                    passive: true,
                })
                this.listeningToGlobalClick = true
            }
        } else {
            if (this.listeningToGlobalClick) {
                document.body.removeEventListener("mousedown", this.onGlobalClick)
                this.listeningToGlobalClick = false
            }
        }
    }

    componentWillUnmount() {
        document.body.removeEventListener("mousedown", this.onGlobalClick)
    }

    onGlobalClick = (ev: MouseEvent) => {
        let target = ev.target as HTMLElement
        while (target.parentElement !== null) {
            if (target === this.container) return

            target = target.parentElement
        }
        this.closeMenu()
    }

    closeAndCallback = (val: a) => {
        this.closeMenu()
        this.props.onSelect(val)
    }

    openMenu = () => this.setState({ isExpanded: true })

    closeMenu = () => this.setState({ isExpanded: false })
}

// package/ui/components/menu/menu.svelte
<script>import { createEventDispatcher } from "svelte";
import { onMount } from "svelte";
export let choices;
export let show;
const dispatch = createEventDispatcher();
let containerRef = null;
let isExpanded = false;
const onGlobalClick = (ev) => {
    if (!isExpanded) {
        return;
    }
    let target = ev.target;
    while (target.parentElement !== null) {
        if (target === containerRef) {
            return;
        }
        target = target.parentElement;
    }
    closeMenu();
};
const openMenu = () => {
    isExpanded = true;
};
const closeMenu = () => {
    isExpanded = false;
};
const closeAndCallback = (val) => {
    dispatch("select", val);
    closeMenu();
};
onMount(() => {
    document.body.addEventListener("mousedown", onGlobalClick, {
        passive: true,
    });
    return () => {
        document.body.removeEventListener("mousedown", onGlobalClick);
    };
});
</script>

<!-- svelte-ignore a11y-click-events-have-key-events -->
<div on:blur={closeMenu} bind:this={containerRef} class="container">
    <div class={isExpanded ? "selectedDisplayExpanded" : "selectedDisplay"} on:click={openMenu}>
        {show(choices.focus)}
    </div>
    {#if isExpanded}
        <div
            class="selectableOptions"
            style={`margin-top: ${
                containerRef == null
                    ? "auto"
                    : `calc(-0.5rem - ${containerRef.getBoundingClientRect().height}px)`
            };`}
        >
            <div>
                {#each choices.getLeft() as val}
                    <div class="optionDefault" on:click={() => closeAndCallback(val)}>
                        {show(val)}
                    </div>
                {/each}
                <div class="optionSelected" on:click={closeMenu}>
                    {show(choices.focus)}
                </div>
                {#each choices.getRight() as val}
                    <div class="optionDefault" on:click={() => closeAndCallback(val)}>
                        {show(val)}
                    </div>
                {/each}
            </div>
        </div>
    {/if}
</div>

<style>/*
 * css variables don't get typechecked, and it's very hard to refactor them, so we prefer
 * to use these scss variables that refer to the css variables, since the scss has to be compiled,
 * and the compilation will fail when scss-variables are undefined.
 */
.container {
  background-color: var(--color-surface);
  color: var(--color-onSurface);
  min-width: 6rem;
}

.selectedDisplay {
  cursor: pointer;
  text-align: center;
  min-width: 100%;
  padding: 0.25rem 0.5rem;
  border-radius: 0.25rem;
}
.selectedDisplay:hover {
  background-color: var(--color-secondary);
  color: var(--color-onSecondary);
}

.selectedDisplayExpanded {
  cursor: pointer;
  text-align: center;
  min-width: 100%;
  padding: 0.25rem 0.5rem;
  border-radius: 0.25rem;
  background-color: var(--color-secondary);
  color: var(--color-onSecondary);
}

.selectableOptions {
  position: absolute;
  flex-direction: column;
  min-width: 6rem;
  margin-top: 1px;
  background-color: var(--color-surface);
  color: var(--color-onSurface);
  box-shadow: var(--shadows-menu);
}
.selectableOptions > :first-child {
  border-top-left-radius: 0.25rem;
  border-top-right-radius: 0.25rem;
}
.selectableOptions > :last-child {
  border-bottom-left-radius: 0.25rem;
  border-bottom-right-radius: 0.25rem;
}

.optionDefault {
  cursor: pointer;
  padding: 0.25rem 0.5rem;
}
.optionDefault:hover {
  background-color: var(--color-secondaryLight);
}

.optionSelected {
  cursor: pointer;
  padding: 0.25rem 0.5rem;
  background-color: var(--color-secondary);
  color: var(--color-onSecondary);
}</style>
