// src/lib/ui/components/color-wheel/color-wheel.svelte
<script lang="ts">
    import * as Color from "color";
    import { onMount } from "svelte";
    import { ColorMode, clamp, CanvasPool } from "../../../util";
    import { GlState, type ThumbPositions } from "./color-wheel-logic";

    export let color: Color.Hsluv;
    export let colorType: ColorMode; // = ColorMode.Hsluv;
    export let onChange: (color: Color.Hsluv) => void;

    const enum PointerState {
        Default,
        DownOnInner,
        DownOnOuter,
    }

    const MARGIN = (1 - 0.55) / 2;
    type WithClientXY = Readonly<{
        clientX: number;
        clientY: number;
    }>;

    let containerRef: HTMLDivElement | undefined;
    let canvasContainerRef: HTMLDivElement | undefined;
    let glState: GlState | null = null;
    let pointerState = PointerState.Default;
    let thumbData: ThumbPositions | null = null;

    function signalOuter(ev: WithClientXY) {
        if (!containerRef) {
            return;
        }
        // get xy delta from the center of the ring
        const bounds = containerRef.getBoundingClientRect();
        const x = ev.clientX - bounds.left - bounds.width * 0.5;
        const y = ev.clientY - bounds.top - bounds.height * 0.5;

        // calculate radians of the delta
        const rad = Math.atan2(y, x);

        // get hue from radians (keep in mind the ring is turned 50%)
        const hue = rad / (Math.PI * 2) + 0.5;

        switch (colorType) {
            case ColorMode.Hsv: {
                const hsv = Color.rgbToHsv(color.toRgb());
                onChange(Color.rgbToHsluv(hsv.with({ h: hue }).toRgb()));
                break;
            }
            case ColorMode.Hsluv: {
                onChange(color.with({ h: hue * 360 }));
                break;
            }
        }
    }

    function signalInner(ev: WithClientXY) {
        if (!containerRef) {
            return;
        }
        const bounds = containerRef.getBoundingClientRect();
        const marginX = bounds.width * MARGIN;
        const marginY = bounds.height * MARGIN;

        const width = bounds.width - marginX * 2;
        const height = bounds.height - marginY * 2;

        const x = clamp(ev.clientX - bounds.left - marginX, 0, width);
        const y = clamp(ev.clientY - bounds.top - marginY, 0, height);

        const pctX = x / width;
        const pctY = 1 - y / height;

        switch (colorType) {
            case ColorMode.Hsv: {
                const hue = Color.rgbToHsv(color.toRgb()).h;
                onChange(Color.rgbToHsluv(Color.hsvToRgb(new Color.Hsv(hue, pctX, pctY))));
                break;
            }
            case ColorMode.Hsluv: {
                const hue = color.h;
                onChange(new Color.Hsluv(hue, pctX * 100, pctY * 100));
                break;
            }
        }
    }

    onMount(() => {
        const canvasContainer = canvasContainerRef;
        if (canvasContainer == null) {
            throw { "canvas container ref not found": canvasContainerRef };
        }

        const canvas = CanvasPool.getCanvas({ width: 160, height: 160 });
        canvasContainer.appendChild(canvas);

        glState = new GlState(canvas);
        glState.render(colorType, color);
        thumbData = glState.getThumbPositions(colorType, color);

        return () => {
            if (!glState) {
                return;
            }
            canvasContainerRef?.removeChild(glState.canvas);
            glState.dispose();
            CanvasPool.recycle(glState.canvas);
        };
    });

    {
        function onUp(_ev: WithClientXY) {
            pointerState = PointerState.Default;
        }

        function onMove(ev: WithClientXY) {
            switch (pointerState) {
                case PointerState.Default:
                    break;
                case PointerState.DownOnInner:
                    signalInner(ev);
                    break;
                case PointerState.DownOnOuter:
                    signalOuter(ev);
                    break;
            }
        }

        onMount(() => {
            window.addEventListener("mouseup", onUp);
            window.addEventListener("mouseleave", onUp);
            window.addEventListener("mousemove", onMove, { passive: true });
            return () => {
                window.removeEventListener("mouseup", onUp);
                window.removeEventListener("mouseleave", onUp);
                window.removeEventListener("mousemove", onMove);
            };
        });
    }

    function isInclusive(n: number, min: number, max: number): boolean {
        return n >= min && n <= max;
    }

    function onDown(ev: WithClientXY) {
        if (!containerRef) {
            return;
        }
        const bounds = containerRef.getBoundingClientRect();
        const x = clamp(ev.clientX - bounds.left, 0, bounds.width);
        const y = clamp(ev.clientY - bounds.top, 0, bounds.height);

        const marginX = bounds.width * MARGIN;
        const marginY = bounds.height * MARGIN;

        const isInner =
            isInclusive(x, marginX, bounds.width - marginX) &&
            isInclusive(y, marginY, bounds.height - marginY);

        if (isInner) {
            pointerState = PointerState.DownOnInner;
            signalInner(ev);
        } else {
            pointerState = PointerState.DownOnOuter;
            signalOuter(ev);
        }
    }
</script>

<div class="container" bind:this={containerRef} on:mousedown={onDown}>
    <div>
        <div bind:this={canvasContainerRef} />
        <div
            class="circleThumb"
            style={thumbData === null
                ? undefined
                : `left: ${thumbData.circleThumbX}px; top: ${
                      thumbData.circleThumbY
                  }px; background-color: ${color.toStyle()}; border-color: ${
                      color.l > 50 ? "black" : "white"
                  }; transform: rotate(${thumbData.angle}deg)`}
        />
        <div
            class="areaThumb"
            style={thumbData === null
                ? undefined
                : `left: ${thumbData.areaThumbX}px; top: ${
                      thumbData.areaThumbY
                  }px; background-color: ${color.toStyle()}; border-color: ${
                      color.l > 50 ? "black" : "white"
                  }`}
        />
    </div>
</div>

<style lang="scss">
    .container {
        display: flex;
        justify-content: center;
        width: 100%;
    }

    .circleThumb {
        z-index: 100;
        position: absolute;
        width: 1rem;
        height: 0.5rem;
        margin-left: calc(-0.5rem - 0.05rem);
        margin-top: calc(-0.25rem - 0.05rem);
        border-width: 0.1rem;
        border-style: solid;
    }

    .areaThumb {
        z-index: 100;
        position: absolute;
        width: 0.75rem;
        height: 0.75rem;
        margin-left: calc(-0.375rem - 0.05rem);
        margin-top: calc(-0.375rem - 0.05rem);
        border-width: 0.1rem;
        border-style: solid;
        border-radius: 0.375rem;
    }
</style>

// src/views/colorWheel.tsx
import * as React from "react"
import styled from "../styled"
import * as Color from "color"
import { DEFINE_TAU, createProgram, DEFINE_hsluv_etc, DEFINE_hsvToRgb } from "../webgl"
import { ColorMode } from "../util"

export interface ColorWheelProps {
    readonly color: Color.Hsluv
    readonly colorType: ColorMode
    readonly onChange: (color: Color.Hsluv) => void
}

const Container = styled.div`
    display: flex;
    justify-content: center;
    width: 100%;
`

const enum PointerState {
    Default,
    DownOnInner,
    DownOnOuter,
}

const MARGIN = (1 - 0.55) / 2
type WithClientXY = Readonly<{
    clientX: number
    clientY: number
}>

interface GlState {
    readonly gl: WebGLRenderingContext
    readonly ringRenderer: RingRenderer
    readonly satValRenderer: SatValRenderer
}

const CicleThumb = styled.div`
    z-index: 100;
    position: absolute;
    width: 1rem;
    height: 0.5rem;
    margin-left: calc(-0.5rem - 0.05rem);
    margin-top: calc(-0.25rem - 0.05rem);
    border-width: 0.1rem;
    border-style: solid;
`

const AreaThumb = styled.div`
    z-index: 100;
    position: absolute;
    width: 0.75rem;
    height: 0.75rem;
    margin-left: calc(-0.375rem - 0.05rem);
    margin-top: calc(-0.375rem - 0.05rem);
    border-width: 0.1rem;
    border-style: solid;
    border-radius: 0.375rem;
`

export function ColorWheel(props: ColorWheelProps): JSX.Element {
    const container = React.useRef<HTMLDivElement | null>(null)
    const canvas = React.useRef<HTMLCanvasElement | null>(null)
    const [glState, setGlState] = React.useState<GlState | null>(null)
    const pointerState = React.useRef(PointerState.Default)

    function signalOuter(ev: WithClientXY) {
        // get xy delta from the center of the ring
        const bounds = container.current!.getBoundingClientRect()
        const x = ev.clientX - bounds.left - bounds.width * 0.5
        const y = ev.clientY - bounds.top - bounds.height * 0.5

        // calculate radians of the delta
        const rad = Math.atan2(y, x)

        // get hue from radians (keep in mind the ring is turned 50%)
        const hue = rad / (Math.PI * 2) + 0.5

        const prevColor = props.color
        switch (props.colorType) {
            case ColorMode.Hsv: {
                const hsv = Color.rgbToHsv(props.color.toRgb())
                props.onChange(Color.rgbToHsluv(hsv.with({ h: hue }).toRgb()))
                break
            }
            case ColorMode.Hsluv: {
                props.onChange(prevColor.with({ h: hue * 360 }))
                break
            }
        }
    }

    function signalInner(ev: WithClientXY) {
        const bounds = container.current!.getBoundingClientRect()
        const marginX = bounds.width * MARGIN
        const marginY = bounds.height * MARGIN

        const width = bounds.width - marginX * 2
        const height = bounds.height - marginY * 2

        const x = clamp(ev.clientX - bounds.left - marginX, 0, width)
        const y = clamp(ev.clientY - bounds.top - marginY, 0, height)

        const pctX = x / width
        const pctY = 1 - y / height

        switch (props.colorType) {
            case ColorMode.Hsv: {
                const hue = Color.rgbToHsv(props.color.toRgb()).h
                props.onChange(Color.rgbToHsluv(Color.hsvToRgb(new Color.Hsv(hue, pctX, pctY))))
                break
            }
            case ColorMode.Hsluv: {
                const hue = props.color.h
                props.onChange(new Color.Hsluv(hue, pctX * 100, pctY * 100))
                break
            }
        }
    }

    function onDown(ev: WithClientXY) {
        const bounds = container.current!.getBoundingClientRect()
        const x = clamp(ev.clientX - bounds.left, 0, bounds.width)
        const y = clamp(ev.clientY - bounds.top, 0, bounds.height)

        const marginX = bounds.width * MARGIN
        const marginY = bounds.height * MARGIN

        const isInner =
            isInclusive(x, marginX, bounds.width - marginX) &&
            isInclusive(y, marginY, bounds.height - marginY)

        if (isInner) {
            pointerState.current = PointerState.DownOnInner
            signalInner(ev)
        } else {
            pointerState.current = PointerState.DownOnOuter
            signalOuter(ev)
        }
    }

    function onUp(_ev: WithClientXY) {
        pointerState.current = PointerState.Default
    }

    function onMove(ev: WithClientXY) {
        switch (pointerState.current) {
            case PointerState.Default:
                break
            case PointerState.DownOnInner:
                signalInner(ev)
                break
            case PointerState.DownOnOuter:
                signalOuter(ev)
                break
        }
    }

    React.useEffect(() => {
        if (canvas.current === null) {
            return
        }

        const gl = canvas.current.getContext("webgl")
        if (gl === null) throw "Failed to init webgl"

        gl.blendFunc(WebGLRenderingContext.ONE, WebGLRenderingContext.ONE_MINUS_SRC_ALPHA)
        gl.enable(WebGLRenderingContext.BLEND)
        gl.disable(WebGLRenderingContext.DEPTH_TEST)

        const glState: GlState = {
            gl,
            ringRenderer: new RingRenderer(gl),
            satValRenderer: new SatValRenderer(gl),
        }

        setGlState(glState)

        return () => {
            glState.ringRenderer.dispose()
            glState.satValRenderer.dispose()
        }
    }, [canvas.current])

    React.useEffect(() => {
        if (glState === null) {
            return
        }
        // render
        glState.gl.clearColor(0, 0, 0, 0)
        glState.gl.clear(WebGLRenderingContext.COLOR_BUFFER_BIT)
        glState.ringRenderer!.render(props.colorType, props.color)
        glState.satValRenderer!.render(props.colorType, props.color)
    }, [glState, props.color, props.colorType])

    React.useEffect(() => {
        document.body.addEventListener("mousemove", onMove, { passive: true })
        return () => {
            document.body.removeEventListener("mousemove", onMove)
        }
    }, [props.color, props.colorType, props.onChange])

    React.useEffect(() => {
        document.body.addEventListener("mouseup", onUp)
        return () => {
            document.body.removeEventListener("mouseup", onUp)
        }
    }, [])

    const canvasRect = canvas.current !== null ? canvas.current.getBoundingClientRect() : null

    let angle: number
    let xPct: number
    let yPct: number
    if (props.colorType === ColorMode.Hsluv) {
        angle = (props.color.h + 180) % 360
        xPct = props.color.s / 100
        yPct = props.color.l / 100
    } else {
        const hsv = Color.rgbToHsv(props.color.toRgb())
        angle = (hsv.h * 360 + 180) % 360
        xPct = hsv.s
        yPct = hsv.v
    }

    let circleThumbX = 0
    let circleThumbY = 0
    if (canvasRect !== null) {
        const radius = 80
        const cx = canvasRect.left + radius
        const cy = canvasRect.top + radius

        const theta = (angle * Math.PI) / 180
        const dx = (radius - 8) * Math.cos(theta)
        const dy = (radius - 8) * Math.sin(theta)

        circleThumbX = cx + dx
        circleThumbY = cy + dy
    }

    let areaThumbX = 0
    let areaThumbY = 0
    if (canvasRect !== null) {
        const offset = canvasRect.width * 0.225
        const width = canvasRect.width * 0.55

        areaThumbX = canvasRect.left + offset + width * xPct
        areaThumbY = canvasRect.top + offset + width * (1 - yPct)
    }

    return (
        <Container>
            <div onMouseDown={onDown} ref={container}>
                <canvas width="160" height="160" ref={canvas} />
                <CicleThumb
                    style={{
                        left: circleThumbX,
                        top: circleThumbY,
                        backgroundColor: props.color.toStyle(),
                        borderColor: props.color.l > 50 ? "black" : "white",
                        transform: "rotate(" + angle + "deg)",
                    }}
                />
                <AreaThumb
                    style={{
                        left: areaThumbX,
                        top: areaThumbY,
                        backgroundColor: props.color.toStyle(),
                        borderColor: props.color.l > 50 ? "black" : "white",
                    }}
                />
            </div>
        </Container>
    )
}

function clamp(x: number, min: number, max: number): number {
    return x < min ? min : x > max ? max : x
}

function isInclusive(n: number, min: number, max: number): boolean {
    return n >= min && n <= max
}

const RING_VERT_SRC = `
precision highp float;

attribute vec2 a_position;

varying vec2 v_position;

void main() {
    gl_Position = vec4(a_position, 0.0, 1.0);

    v_position = a_position;
}
`

function makeRingFragSrc(DEFINE_toRgb: string) {
    return `
    precision highp float;
    
    ${DEFINE_TAU}

    ${DEFINE_toRgb}
    
    #define INNER_RAD1 0.83
    #define INNER_RAD2 0.85
    #define OUTER_RAD1 0.98
    #define OUTER_RAD2 1.00
    
    varying vec2 v_position;
    
    uniform vec3 u_color;
    
    void main() {
        vec2 pos = v_position * vec2(1.0, -1.0);
        float dist = sqrt(dot(pos, pos));
    
        float a = smoothstep(INNER_RAD1, INNER_RAD2, dist) - smoothstep(OUTER_RAD1, OUTER_RAD2, dist);
    
        float radians = atan(pos.y, pos.x);
        float hue = (radians / TAU) + 0.5;
    
        vec3 hsluv = vec3(hue, 1.0, a);
    
        gl_FragColor = vec4(toRgb(u_color, hsluv) * a, a);
    }
    `
}

const RING_FRAG_SRC_HSV = makeRingFragSrc(`
${DEFINE_hsvToRgb}

vec3 toRgb(vec3 color, vec3 xyz) {
    return hsvToRgb(xyz);
}
`)

const RING_FRAG_SRC_HSLUV = makeRingFragSrc(`
${DEFINE_hsluv_etc}

vec3 toRgb(vec3 color, vec3 xyz) {
    return hsluvToRgb(xyz * vec3(360.0, color.y, color.z));
}
`)

class RingRenderer {
    private readonly buffer: WebGLBuffer
    private program: WebGLProgram | null = null
    private colorLocation: WebGLUniformLocation | null = null
    private prevColorType: ColorMode | null = null

    constructor(private readonly gl: WebGLRenderingContext) {
        this.buffer = gl.createBuffer()!
        gl.bindBuffer(WebGLRenderingContext.ARRAY_BUFFER, this.buffer)
        gl.bufferData(
            WebGLRenderingContext.ARRAY_BUFFER,
            new Float32Array([1.0, 1.0, -1.0, 1.0, 1.0, -1.0, -1.0, -1.0]),
            WebGLRenderingContext.STATIC_DRAW
        )
    }

    render(colorType: ColorMode, color: Color.Hsluv): void {
        if (!this.program || this.prevColorType !== colorType) {
            if (this.program) {
                this.gl.deleteProgram(this.program)
            }

            switch (colorType) {
                case ColorMode.Hsv:
                    this.program = createProgram(this.gl, RING_VERT_SRC, RING_FRAG_SRC_HSV)!
                    break
                case ColorMode.Hsluv:
                    this.program = createProgram(this.gl, RING_VERT_SRC, RING_FRAG_SRC_HSLUV)!
                    break
            }
            this.gl.bindAttribLocation(this.program!, 0, "a_position")
            this.colorLocation = this.gl.getUniformLocation(this.program!, "u_color")!
            this.prevColorType = colorType
        }

        this.gl.useProgram(this.program)
        this.gl.bindBuffer(WebGLRenderingContext.ARRAY_BUFFER, this.buffer)

        this.gl.vertexAttribPointer(0, 2, WebGLRenderingContext.FLOAT, false, 0, 0)
        this.gl.enableVertexAttribArray(0)

        switch (colorType) {
            case ColorMode.Hsv: {
                const hsv = Color.rgbToHsv(Color.hsluvToRgb(color))
                this.gl.uniform3f(this.colorLocation, hsv.h, hsv.s, hsv.v)
                break
            }
            case ColorMode.Hsluv: {
                this.gl.uniform3f(this.colorLocation, color.h, color.s, color.l)
                break
            }
        }

        this.gl.drawArrays(WebGLRenderingContext.TRIANGLE_STRIP, 0, 4)
    }

    dispose(): void {
        this.gl.deleteBuffer(this.buffer)
        this.gl.deleteProgram(this.program)
    }
}

const WI = 0.55

const SATVAL_VERT_SRC = `
precision highp float;

attribute vec2 a_position;

varying vec2 v_tex_position;

void main() {
    gl_Position = vec4(a_position, 0.0, 1.0);

    v_tex_position = ((a_position / ${WI.toFixed(2)}) + 1.0) / 2.0;
}
`

function makeSatValFragSrc(DEFINE_toRgb: string): string {
    return `
    precision highp float;

    ${DEFINE_toRgb}
    
    varying vec2 v_tex_position;
    
    uniform vec3 u_color;
    
    void main() {
        // mix saturation from left to right [0, 1]
        // mix value from bottom to top: [0, 1]
        float x = v_tex_position.x;
        float y = v_tex_position.y;
    
        gl_FragColor = vec4(
            toRgb(u_color.x, x, y),
            1.0
        );
    }
    `
}

const SATVAL_FRAG_SRC_HSV = makeSatValFragSrc(`
${DEFINE_hsvToRgb}

vec3 toRgb(float hue, float x, float y) {
    return hsvToRgb(vec3(hue, x, y));
}
`)

const SATVAL_FRAG_SRC_HSLUV = makeSatValFragSrc(`
${DEFINE_hsluv_etc}

vec3 toRgb(float hue, float x, float y) {
    return hsluvToRgb(vec3(hue, x * 100.0, y * 100.0));
}
`)

class SatValRenderer {
    private readonly buffer: WebGLBuffer
    private colorLocation: WebGLUniformLocation | null = null
    private program: WebGLProgram | null = null
    private prevColor: Color.Hsluv | null = null

    constructor(private readonly gl: WebGLRenderingContext) {
        this.buffer = gl.createBuffer()!
        gl.bindBuffer(WebGLRenderingContext.ARRAY_BUFFER, this.buffer)
        gl.bufferData(
            WebGLRenderingContext.ARRAY_BUFFER,
            new Float32Array([
                // 1
                WI,
                WI,
                // 2
                -WI,
                WI,
                // 3
                WI,
                -WI,
                // 4
                -WI,
                WI,
                // 5
                WI,
                -WI,
                // 6
                -WI,
                -WI,
            ]),
            WebGLRenderingContext.STATIC_DRAW
        )
    }

    render(colorType: ColorMode, color: Color.Hsluv): void {
        const gl = this.gl

        if (!this.program || this.prevColor!.is(color)) {
            if (this.program) {
                gl.deleteProgram(this.program)
            }

            switch (colorType) {
                case ColorMode.Hsv:
                    this.program = createProgram(gl, SATVAL_VERT_SRC, SATVAL_FRAG_SRC_HSV)!
                    break
                case ColorMode.Hsluv:
                    this.program = createProgram(gl, SATVAL_VERT_SRC, SATVAL_FRAG_SRC_HSLUV)!
                    break
            }
            gl.bindAttribLocation(this.program!, 0, "a_position")
            this.colorLocation = gl.getUniformLocation(this.program!, "u_color")!
        }

        gl.useProgram(this.program)
        gl.bindBuffer(WebGLRenderingContext.ARRAY_BUFFER, this.buffer)

        gl.vertexAttribPointer(0, 2, WebGLRenderingContext.FLOAT, false, 0, 0)
        gl.enableVertexAttribArray(0)

        switch (colorType) {
            case ColorMode.Hsv: {
                const hsv = Color.rgbToHsv(Color.hsluvToRgb(color))
                this.gl.uniform3f(this.colorLocation, hsv.h, hsv.s, hsv.v)
                break
            }
            case ColorMode.Hsluv: {
                this.gl.uniform3f(this.colorLocation, color.h, color.s, color.l)
                break
            }
        }
        this.prevColor = color

        gl.drawArrays(WebGLRenderingContext.TRIANGLES, 0, 6)
    }

    dispose(): void {
        const gl = this.gl
        gl.deleteBuffer(this.buffer)
        gl.deleteProgram(this.program)
    }
}
