// package/ui/components/surface/surface.svelte
<div class="surface">
    <slot />
</div>

<style>/*
 * css variables don't get typechecked, and it's very hard to refactor them, so we prefer
 * to use these scss variables that refer to the css variables, since the scss has to be compiled,
 * and the compilation will fail when scss-variables are undefined.
 */
.surface {
  background-color: var(--color-surface);
  color: var(--color-onSurface);
  box-shadow: var(--shadows-surface);
  pointer-events: all;
  display: flex;
  align-items: center;
  width: 100%;
  overflow: hidden;
  white-space: nowrap;
  user-select: none;
}</style>

// src/views/surface.tsx
import * as React from "react"
import styled from "../styled"

export const SurfaceLook = styled.div`
    background-color: ${p => p.theme.color.surface.toStyle()};
    color: ${p => p.theme.color.onSurface.toStyle()};
    box-shadow: ${p => p.theme.shadows.surface};
`

export const Surface = styled(SurfaceLook)`
    display: flex;
    align-items: center;
    width: 100%;
    overflow: hidden;
    white-space: nowrap;
    user-select: none;
`
