// src/ui/layers/index.tsx
import * as React from "react"
import styled from "styled-components"
import { LayerState, LayerMessageSender } from "canvas/layers"
import { LayerView } from "./layer"
import { DefaultButton } from "ui/views/buttons/filledButton"
import { Row } from "ui/views/row"
import { Slider } from "ui/views/slider"
import { Labeled } from "ui/views/labeled"
import { InlineLabeled } from "ui/views/inlineLabeled"
import { Switch } from "ui/views/switch"
import { CSS_COLOR_TEXT_LIGHT, CSS_COLOR_BG_LEVEL_1, CSS_COLOR_BG_LEVEL_0 } from "ui/css"

export interface LayersProps {
    readonly layers: LayerState
    readonly sender: LayerMessageSender
}

const LayersWrapper = styled.div`
    background-color: ${CSS_COLOR_BG_LEVEL_0};
    height: 100%;
    padding: 0.5rem 0;
    color: ${CSS_COLOR_TEXT_LIGHT};
`

const LayersListWrapper = styled.div`
    padding: 0.5rem;

    & > :not(:first-child) {
        margin-top: 0.25rem;
    }
`

const LayersControlsWrapper = styled.div`
    background-color: ${CSS_COLOR_BG_LEVEL_1};
    display: flex;
    flex-direction: column;
    padding-left: 0.5rem;
    padding-right: 0.5rem;
`

export function Layers({ layers, sender }: LayersProps): JSX.Element {
    const topLayers = layers.layers.children
    const current = layers.current()

    return (
        <LayersWrapper>
            <LayersControlsWrapper>
                <Row spacing="0.25rem">
                    <DefaultButton onClick={() => sender.newLayer(current.id)} title="New layer">
                        New
                    </DefaultButton>
                    <DefaultButton
                        onClick={() => sender.removeLayer(current.id)}
                        title="Remove layer"
                    >
                        Delete
                    </DefaultButton>
                </Row>
                <InlineLabeled label="Hidden">
                    <Switch
                        onCheck={isHidden => sender.setHidden(current.id, isHidden)}
                        checked={current.isHidden}
                    />
                </InlineLabeled>
                <Labeled label="Opacity" value={current.opacity.toFixed(2)}>
                    <Slider
                        onChange={pct => sender.setOpacity(current.id, pct)}
                        percentage={current.opacity}
                    />
                </Labeled>
            </LayersControlsWrapper>
            <LayersListWrapper>
                {topLayers.map(x => (
                    <LayerView
                        layer={x}
                        onClick={id => sender.selectLayer(id)}
                        selectedId={current.id}
                        key={x.id}
                    />
                ))}
            </LayersListWrapper>
        </LayersWrapper>
    )
}

// src/lib/ui/layers/layers.svelte
<script lang="ts">
	import type { State, Sender } from '../../canvas/layers';
	import { Row, DefaultButton, Surface, LabeledSlider, LabeledSwitch } from '../components';
	import { stringToFloat } from '../../util';
	import LayerComponent from './layer.svelte';

	export let layers: State;
	export let sender: Sender;

	$: topLayers = layers.layers.children;
	$: current = layers.current();

	function toFixed2(n: number): string {
		return n.toFixed(2);
	}
</script>

<div class="layersWrapper">
	<Surface>
		<div class="layersControlsWrapper">
			<Row spacing={0.25}>
				<DefaultButton onClick={() => sender.newLayer(current.id)} title="New layer">
					New
				</DefaultButton>
				<DefaultButton onClick={() => sender.removeLayer(current.id)} title="Delete layer">
					Delete
				</DefaultButton>
			</Row>
			<LabeledSwitch
				label="Hidden"
				checked={current.isHidden}
				onCheck={(isHidden) => sender.setHidden(current.id, isHidden)}
			/>
			<LabeledSlider
				label="Opacity"
				value={current.opacity}
				toString={toFixed2}
				fromString={stringToFloat}
				percentage={current.opacity}
				onChange={(pct) => sender.setOpacity(current.id, pct)}
			/>
		</div>
	</Surface>
	<div class="layersListWrapper">
		{#each topLayers as layer}
			<LayerComponent {layer} selectedId={current.id} onClick={(id) => sender.selectLayer(id)} />
		{/each}
	</div>
</div>

<style lang="scss">
	@import '../theme.scss';

	.layersWrapper {
		height: 100%;
	}

	.layersListWrapper {
		display: flex;
		flex-direction: column;
		gap: 0.25rem;
		padding: 0.5rem 0.25rem;
	}

	.layersControlsWrapper {
		display: flex;
		justify-content: space-between;
		flex-direction: column;
		padding-top: 0.5rem;
		padding-left: 0.5rem;
		padding-right: 0.5rem;
		width: 100%;
	}
</style>
