// package/ui/layers/layers.svelte
<script>import { Row, DefaultButton, Surface, Labeled, Slider, Switch } from "../components/index.js";
import { stringToFloat } from "../../util/index.js";
import LayerComponent from "./layer.svelte";
import InlineLabeled from "../components/labeled/inline-labeled.svelte";
export let layers;
export let sender;
$: topLayers = layers.layers.children;
$: current = layers.current();
const sendFloat = (ev, f) => {
    const val = stringToFloat(ev.detail);
    if (val != null) {
        f(val);
    }
};
</script>

<div class="layersWrapper">
    <Surface>
        <div class="layersControlsWrapper">
            <Row spacing={0.25}>
                <DefaultButton
                    on:click={() => sender.newLayer(current.id)}
                    title="New layer"
                    style="width: 100%"
                >
                    New
                </DefaultButton>
                <DefaultButton
                    on:click={() => sender.removeLayer(current.id)}
                    title="Delete layer"
                    style="width: 100%"
                >
                    Delete
                </DefaultButton>
            </Row>
            <InlineLabeled label="Hidden">
                <Switch
                    checked={current.isHidden}
                    on:change={(ev) => sender.setHidden(current.id, ev.detail)}
                />
            </InlineLabeled>
            <Labeled
                label="Opacity"
                value={current.opacity.toFixed(2)}
                on:change={(ev) => sendFloat(ev, (n) => sender.setOpacity(current.id, n))}
            >
                <Slider
                    value={current.opacity}
                    on:change={(ev) => sender.setOpacity(current.id, ev.detail)}
                />
            </Labeled>
        </div>
    </Surface>
    <div class="layersListWrapper">
        {#each topLayers as layer}
            <LayerComponent
                {layer}
                selectedId={current.id}
                onClick={(id) => sender.selectLayer(id)}
            />
        {/each}
    </div>
</div>

<style>/*
 * css variables don't get typechecked, and it's very hard to refactor them, so we prefer
 * to use these scss variables that refer to the css variables, since the scss has to be compiled,
 * and the compilation will fail when scss-variables are undefined.
 */
.layersWrapper {
  height: fit-content;
}

.layersListWrapper {
  display: flex;
  flex-direction: column;
  gap: 0.25rem;
  padding: 0.5rem 0.25rem;
}

.layersControlsWrapper {
  display: flex;
  justify-content: space-between;
  flex-direction: column;
  padding-top: 0.5rem;
  padding-left: 0.5rem;
  padding-right: 0.5rem;
  width: 100%;
}</style>

// src/ui/layers/index.tsx
import * as React from "react"
import styled from "styled-components"
import { LayerState, LayerMessageSender } from "canvas/layers"
import { LayerView } from "./layer"
import { DefaultButton } from "ui/views/buttons/filledButton"
import { Row } from "ui/views/row"
import { Slider } from "ui/views/slider"
import { Labeled } from "ui/views/labeled"
import { InlineLabeled } from "ui/views/inlineLabeled"
import { Switch } from "ui/views/switch"
import { CSS_COLOR_TEXT_LIGHT, CSS_COLOR_BG_LEVEL_1, CSS_COLOR_BG_LEVEL_0 } from "ui/css"

export interface LayersProps {
    readonly layers: LayerState
    readonly sender: LayerMessageSender
}

const LayersWrapper = styled.div`
    background-color: ${CSS_COLOR_BG_LEVEL_0};
    height: 100%;
    padding: 0.5rem 0;
    color: ${CSS_COLOR_TEXT_LIGHT};
`

const LayersListWrapper = styled.div`
    padding: 0.5rem;

    & > :not(:first-child) {
        margin-top: 0.25rem;
    }
`

const LayersControlsWrapper = styled.div`
    background-color: ${CSS_COLOR_BG_LEVEL_1};
    display: flex;
    flex-direction: column;
    padding-left: 0.5rem;
    padding-right: 0.5rem;
`

export function Layers({ layers, sender }: LayersProps): JSX.Element {
    const topLayers = layers.layers.children
    const current = layers.current()

    return (
        <LayersWrapper>
            <LayersControlsWrapper>
                <Row spacing="0.25rem">
                    <DefaultButton onClick={() => sender.newLayer(current.id)} title="New layer">
                        New
                    </DefaultButton>
                    <DefaultButton
                        onClick={() => sender.removeLayer(current.id)}
                        title="Remove layer"
                    >
                        Delete
                    </DefaultButton>
                </Row>
                <InlineLabeled label="Hidden">
                    <Switch
                        onCheck={isHidden => sender.setHidden(current.id, isHidden)}
                        checked={current.isHidden}
                    />
                </InlineLabeled>
                <Labeled label="Opacity" value={current.opacity.toFixed(2)}>
                    <Slider
                        onChange={pct => sender.setOpacity(current.id, pct)}
                        percentage={current.opacity}
                    />
                </Labeled>
            </LayersControlsWrapper>
            <LayersListWrapper>
                {topLayers.map(x => (
                    <LayerView
                        layer={x}
                        onClick={id => sender.selectLayer(id)}
                        selectedId={current.id}
                        key={x.id}
                    />
                ))}
            </LayersListWrapper>
        </LayersWrapper>
    )
}
