// src/views/menu.tsx
import * as React from "react"
import styled, { Rem } from "../styled"
import { ZipperList } from "../collections/zipperList"

export interface Props<a> {
    readonly choices: ZipperList<a>
    readonly show: (val: a) => string
    readonly onSelect: (val: a) => void
}

const Container = styled.div`
    background-color: ${p => p.theme.color.surface.toStyle()};
    color: ${p => p.theme.color.onSurface.toStyle()};
    min-width: 6rem;
`

const SelectedDisplayCommon = styled.div`
    cursor: pointer;
    text-align: center;
    min-width: 100%;
    padding: 0.25rem 0.5rem;
    border-radius: 0.25rem;
`

const SelectedDisplay = styled(SelectedDisplayCommon)`
    &:hover {
        background-color: ${p => p.theme.color.secondary.toStyle()};
        color: ${p => p.theme.color.onSecondary.toStyle()};
    }
`

const SelectedDisplayExpanded = styled(SelectedDisplayCommon)`
    background-color: ${p => p.theme.color.secondary.toStyle()};
    color: ${p => p.theme.color.onSecondary.toStyle()};
`

const SelectableOptions = styled.div`
    position: absolute;
    flex-direction: column;
    min-width: 6rem;
    margin-top: 1px;
    background-color: ${p => p.theme.color.surface.toStyle()};
    color: ${p => p.theme.color.onSurface.toStyle()};
    box-shadow: ${p => p.theme.shadows.menu};

    > :first-child {
        border-top-left-radius: 0.25rem;
        border-top-right-radius: 0.25rem;
    }
    > :last-child {
        border-bottom-left-radius: 0.25rem;
        border-bottom-right-radius: 0.25rem;
    }
`

const OptionCommon = styled.div`
    cursor: pointer;
    padding: 0.25rem 0.5rem;
`

const OptionDefault = styled(OptionCommon)`
    &:hover {
        background-color: ${p => p.theme.color.secondaryLight.toStyle()};
    }
`

const OptionSelected = styled(OptionCommon)`
    background-color: ${p => p.theme.color.secondary.toStyle()};
    color: ${p => p.theme.color.onSecondary.toStyle()};
`

interface State {
    readonly isExpanded: boolean
}

export class Menu<a> extends React.Component<Props<a>, State> {
    state = { isExpanded: false }
    container: HTMLDivElement | null = null
    listeningToGlobalClick: boolean = false

    render(): JSX.Element {
        const { choices, show } = this.props

        return (
            <Container onBlur={this.closeMenu}>
                <div ref={x => (this.container = x)}>
                    {this.state.isExpanded ? (
                        <>
                            <SelectedDisplayExpanded onMouseDown={this.closeMenu}>
                                {show(choices.focus)}
                            </SelectedDisplayExpanded>
                            <SelectableOptions
                                style={{
                                    marginTop:
                                        "calc(-0.5rem - " +
                                        this.container!.getBoundingClientRect().height +
                                        "px)",
                                }}
                            >
                                {choices.getLeft().map(value => (
                                    <OptionDefault
                                        key={show(value)}
                                        onClick={() => this.closeAndCallback(value)}
                                    >
                                        {show(value)}
                                    </OptionDefault>
                                ))}
                                <OptionSelected key={show(choices.focus)} onClick={this.closeMenu}>
                                    {show(choices.focus)}
                                </OptionSelected>
                                {choices.getRight().map(value => (
                                    <OptionDefault
                                        key={show(value)}
                                        onClick={() => this.closeAndCallback(value)}
                                    >
                                        {show(value)}
                                    </OptionDefault>
                                ))}
                            </SelectableOptions>
                        </>
                    ) : (
                        <SelectedDisplay onMouseDown={this.openMenu}>
                            {/* {show(choices.focus)} */}
                        </SelectedDisplay>
                    )} 
                </div>
            </Container>
        )
    }

    componentDidUpdate() {
        if (this.state.isExpanded) {
            if (!this.listeningToGlobalClick) {
                document.body.addEventListener("mousedown", this.onGlobalClick, {
                    passive: true,
                })
                this.listeningToGlobalClick = true
            }
        } else {
            if (this.listeningToGlobalClick) {
                document.body.removeEventListener("mousedown", this.onGlobalClick)
                this.listeningToGlobalClick = false
            }
        }
    }

    componentWillUnmount() {
        document.body.removeEventListener("mousedown", this.onGlobalClick)
    }

    onGlobalClick = (ev: MouseEvent) => {
        let target = ev.target as HTMLElement
        while (target.parentElement !== null) {
            if (target === this.container) return

            target = target.parentElement
        }
        this.closeMenu()
    }

    closeAndCallback = (val: a) => {
        this.closeMenu()
        this.props.onSelect(val)
    }

    openMenu = () => this.setState({ isExpanded: true })

    closeMenu = () => this.setState({ isExpanded: false })
}

// src/lib/ui/components/menu/menu.svelte
<script lang="ts">
  import { onMount } from "svelte";
  import type { ZipperList } from "../../../collections/zipperList";

  type a = $$Generic;

  export let choices: ZipperList<a>;
  export let show: (val: a) => string;
  export let onSelect: (val: a) => void;

  let containerRef: HTMLDivElement | null = null;
  let isExpanded = false;

  const onGlobalClick = (ev: MouseEvent) => {
    if (!isExpanded) {
      return;
    }
    let target = ev.target as HTMLElement;
    while (target.parentElement !== null) {
      if (target === containerRef) {
        return;
      }

      target = target.parentElement;
    }
    closeMenu();
  };

  const openMenu = () => {
    isExpanded = true;
  };

  const closeMenu = () => {
    isExpanded = false;
  };

  const closeAndCallback = (val: a) => {
    onSelect(val);
    closeMenu();
  };

  onMount(() => {
    document.body.addEventListener("mousedown", onGlobalClick, {
      passive: true,
    });
    return () => {
      document.body.removeEventListener("mousedown", onGlobalClick);
    };
  });
</script>

<!-- svelte-ignore a11y-click-events-have-key-events -->
<div on:blur={closeMenu} bind:this={containerRef} class="container">
  <div class={isExpanded ? "selectedDisplayExpanded" : "selectedDisplay"} on:click={openMenu}>
    {show(choices.focus)}
  </div>
  {#if isExpanded}
    <div
      class="selectableOptions"
      style={`margin-top: ${
        containerRef == null
          ? "auto"
          : `calc(-0.5rem - ${containerRef.getBoundingClientRect().height}px)`
      };`}
    >
      <div>
        {#each choices.getLeft() as val}
          <div class="optionDefault" on:click={() => closeAndCallback(val)}>
            {show(val)}
          </div>
        {/each}
        <div class="optionSelected" on:click={closeMenu}>
          {show(choices.focus)}
        </div>
        {#each choices.getRight() as val}
          <div class="optionDefault" on:click={() => closeAndCallback(val)}>
            {show(val)}
          </div>
        {/each}
      </div>
    </div>
  {/if}
</div>

<style lang="scss">
  @import "../../theme.scss";

  .container {
    background-color: $color-surface;
    color: $color-onSurface;
    min-width: 6rem;
  }

  @mixin selectedDisplayCommon {
    cursor: pointer;
    text-align: center;
    min-width: 100%;
    padding: 0.25rem 0.5rem;
    border-radius: 0.25rem;
  }

  .selectedDisplay {
    @include selectedDisplayCommon;
    &:hover {
      background-color: $color-secondary;
      color: $color-onSecondary;
    }
  }

  .selectedDisplayExpanded {
    @include selectedDisplayCommon;
    background-color: $color-secondary;
    color: $color-onSecondary;
  }

  .selectableOptions {
    position: absolute;
    flex-direction: column;
    min-width: 6rem;
    margin-top: 1px;
    background-color: $color-surface;
    color: $color-onSurface;
    box-shadow: $shadows-menu;

    > :first-child {
      border-top-left-radius: 0.25rem;
      border-top-right-radius: 0.25rem;
    }
    > :last-child {
      border-bottom-left-radius: 0.25rem;
      border-bottom-right-radius: 0.25rem;
    }
  }

  @mixin optionCommon {
    cursor: pointer;
    padding: 0.25rem 0.5rem;
  }

  .optionDefault {
    @include optionCommon;
    &:hover {
      background-color: $color-secondaryLight;
    }
  }

  .optionSelected {
    @include optionCommon;
    background-color: $color-secondary;
    color: $color-onSecondary;
  }
</style>
