// package/ui/toolbar/toolbar.svelte
<script>import { Brush } from "../brush";
import { Eraser } from "../eraser";
import { SinkableButton, Icons } from "../components";
export let sender;
export let tool;
export let transientState;
$: currentToolType = tool.current;
</script>

<div class="toolBarContainer">
    <div class="surfaceLike leftBar">
        <SinkableButton
            isDown={currentToolType === "Brush"}
            on:click={() => sender.setTool("Brush")}
        >
            <Icons.Brush24 />
        </SinkableButton>
        <SinkableButton
            isDown={currentToolType === "Eraser"}
            on:click={() => sender.setTool("Eraser")}
        >
            <Icons.Edit24 />
        </SinkableButton>
        <SinkableButton isDown={currentToolType === "Zoom"} on:click={() => sender.setTool("Zoom")}>
            <Icons.Search24 />
        </SinkableButton>
    </div>
    {#if transientState.isDetailsExpanded}
        {#if currentToolType === "Brush"}
            <Brush brush={tool.brush} sender={sender.brush} />
        {:else if currentToolType === "Eraser"}
            <Eraser brush={tool.eraser} sender={sender.eraser} />
        {/if}
    {/if}
</div>

<style>/*
 * css variables don't get typechecked, and it's very hard to refactor them, so we prefer
 * to use these scss variables that refer to the css variables, since the scss has to be compiled,
 * and the compilation will fail when scss-variables are undefined.
 */
.toolBarContainer {
  display: flex;
  z-index: 1;
}

.leftBar {
  display: flex;
  flex-direction: column;
  padding-top: 1rem;
  margin-right: 0.5rem;
  gap: 0.125rem;
  background-color: var(--color-surface);
  color: var(--color-onSurface);
  box-shadow: var(--shadows-surface);
  pointer-events: all;
}</style>

// src/tools/toolbar.tsx
import * as React from "react"

import styled from "../styled"
import * as Tools from "."
import * as Brush from "./brush"
import * as Eraser from "./eraser"
import { SinkableButton } from "../views/buttons"
import { SurfaceLook } from "../views/surface"

export interface ToolbarProps {
    readonly msgSender: Tools.MsgSender
    readonly tool: Tools.Tool
    readonly transientState: TransientState
}

const LeftBar = styled(SurfaceLook)`
    display: flex;
    flex-direction: column;
    padding-top: 1rem;
    margin-right: 0.5rem;

    > :not(:last-child) {
        margin-bottom: 0.125rem;
    }
    > :not(:last-child) {
        margin-bottom: 0.125rem;
    }
`

const ToolBarContainer = styled.div`
    display: flex;
`
export function View(props: ToolbarProps): JSX.Element {
    const currentToolType = props.tool.current
    const setTool = props.msgSender.setTool

    return (
        <ToolBarContainer>
            <LeftBar>
                <SinkableButton
                    dataKey="brush"
                    onClick={() => setTool(Tools.ToolType.Brush)}
                    isDown={currentToolType === Tools.ToolType.Brush}
                >
                    🖌
                </SinkableButton>
                <SinkableButton
                    dataKey="erase"
                    onClick={() => setTool(Tools.ToolType.Eraser)}
                    isDown={currentToolType === Tools.ToolType.Eraser}
                >
                    🔥
                </SinkableButton>
                <SinkableButton
                    dataKey="zoom"
                    onClick={() => setTool(Tools.ToolType.Zoom)}
                    isDown={currentToolType === Tools.ToolType.Zoom}
                >
                    🔍
                </SinkableButton>
            </LeftBar>
            {props.transientState.isDetailsExpanded ? (
                (() => {
                    switch (currentToolType) {
                        case Tools.ToolType.Brush:
                            return (
                                <Brush.Details
                                    messageSender={props.msgSender.brush}
                                    tool={props.tool.brush}
                                />
                            )
                        case Tools.ToolType.Eraser:
                            return (
                                <Eraser.Details
                                    messageSender={props.msgSender.eraser}
                                    tool={props.tool.eraser}
                                />
                            )
                        default:
                            return <></>
                    }
                })()
            ) : (
                <></>
            )}
        </ToolBarContainer>
    )
}

export interface TransientState {
    readonly isDetailsExpanded: boolean
}
